#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
export QT_QPA_PLATFORMTHEME="qt5ct"
autorandr -c

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

keybLayout=$(setxkbmap -v | awk -F "+" '/symbols/ {print $2}')

# keyboard bindings
if [ $keybLayout = "be" ]; then
  cp ~/.config/leftwm/config-azerty.toml ~/.config/leftwm/config.toml
fi

# keybindings daemon
sxhkd -c ~/.config/leftwm/sxhkd/sxhkdrc &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends --config "$SCRIPTPATH"/picom.conf &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

# Set the theme.toml config
# echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

Set background
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-fill "$SCRIPTPATH"/background.png
fi

# diversity of apps to start
# eww daemon
# dunst -conf "$SCRIPTPATH"/dunst/dunstrc &
nm-applet &
# variety &
# pamac-tray &
xfce4-power-manager &
numlockx on &
# blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &
# conky -c ~/.config/leftwm/system-overview &
#nitrogen --restore &
#caffeine &
#vivaldi-stable &
#firefox &
#thunar &
#dropbox &
#insync start &
#discord &
#spotify &
#atom &
#autorandr horizontal &

#mainbar
index=0
monitors=($(polybar -m | sed s/:.*//))
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  barname="mainbar$index"
  monitor=${monitors[index]} width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar/config.ini $barname &> /dev/null &
  let index=index+1
done
